import type { TeamData } from "@/types";

export const teamData: TeamData = {
  name: "Inner Peace",
  tagline: "Chaos Is Our Canvas. Victory Is Our Peace.",
  founded: "2023",
  region: "Bangladesh",
  discord: "https://discord.gg/YOURLINK",
  twitter: "https://twitter.com/InnerPeaceGG",
  instagram: "https://instagram.com/InnerPeaceGG",
  youtube: "https://youtube.com/InnerPeaceGG",
  facebook: "https://facebook.com/InnerPeaceGG",
  email: "contact@innerpeace.gg",

  games: [
    {
      name: "Valorant",
      status: "Primary",
      rank: "Diamond+",
      color: "#FF4655",
      icon: "/icons/valorant.svg",
    },
    {
      name: "CS2",
      status: "Primary",
      rank: "Faceit Level 8+",
      color: "#F0A500",
      icon: "/icons/cs2.svg",
    },
    {
      name: "Other Titles",
      status: "Casual",
      rank: "Competitive",
      color: "#6366F1",
      icon: "/icons/controller.svg",
    },
  ],

  stats: [
    { label: "Team Members", value: "10+" },
    { label: "Matches Played", value: "200+" },
    { label: "Win Rate", value: "68%" },
    { label: "Discord Members", value: "500+" },
  ],

  roster: [
    {
      id: 1,
      username: "Player1",
      realName: "Real Name",
      role: "IGL",
      game: "Valorant",
      rank: "Immortal 2",
      country: "🇧🇩",
      bio: "The mastermind behind every strat.",
      agents: ["Omen", "Brimstone"],
      stats: { kd: "1.4", hs: "32%", winRate: "71%" },
      social: { twitter: "#", twitch: "#" },
      avatar: `https://ui-avatars.com/api/?name=Player1&background=7C3AED&color=fff&size=128`,
      isCaptain: true,
    },
    {
      id: 2,
      username: "Player2",
      realName: "Real Name",
      role: "Duelist",
      game: "Valorant",
      rank: "Diamond 3",
      country: "🇧🇩",
      bio: "Entry fragger who never misses.",
      agents: ["Jett", "Neon"],
      stats: { kd: "1.6", hs: "38%", winRate: "65%" },
      social: { twitter: "#", twitch: "#" },
      avatar: `https://ui-avatars.com/api/?name=Player2&background=7C3AED&color=fff&size=128`,
      isCaptain: false,
    },
    {
      id: 3,
      username: "Player3",
      realName: "Real Name",
      role: "Sentinel",
      game: "Valorant",
      rank: "Immortal 1",
      country: "🇧🇩",
      bio: "Locking down sites since day one.",
      agents: ["Killjoy", "Sage"],
      stats: { kd: "1.2", hs: "28%", winRate: "69%" },
      social: { twitter: "#", twitch: "#" },
      avatar: `https://ui-avatars.com/api/?name=Player3&background=7C3AED&color=fff&size=128`,
      isCaptain: false,
    },
    {
      id: 4,
      username: "Player4",
      realName: "Real Name",
      role: "Controller",
      game: "Valorant",
      rank: "Diamond 2",
      country: "🇧🇩",
      bio: "Smokes and vision control.",
      agents: ["Viper", "Astra"],
      stats: { kd: "1.1", hs: "25%", winRate: "67%" },
      social: { twitter: "#", twitch: "#" },
      avatar: `https://ui-avatars.com/api/?name=Player4&background=7C3AED&color=fff&size=128`,
      isCaptain: false,
    },
    {
      id: 5,
      username: "Player5",
      realName: "Real Name",
      role: "Initiator",
      game: "Valorant",
      rank: "Diamond 1",
      country: "🇧🇩",
      bio: "Info and entry support.",
      agents: ["Sova", "Breach"],
      stats: { kd: "1.3", hs: "30%", winRate: "64%" },
      social: { twitter: "#", twitch: "#" },
      avatar: `https://ui-avatars.com/api/?name=Player5&background=7C3AED&color=fff&size=128`,
      isCaptain: false,
    },
    {
      id: 6,
      username: "Player6",
      realName: "Real Name",
      role: "AWPer",
      game: "CS2",
      rank: "Faceit 9",
      country: "🇧🇩",
      bio: "AWP specialist.",
      stats: { kd: "1.5", hs: "45%", winRate: "70%" },
      social: { twitter: "#", twitch: "#" },
      avatar: `https://ui-avatars.com/api/?name=Player6&background=7C3AED&color=fff&size=128`,
      isCaptain: false,
    },
    {
      id: 7,
      username: "Player7",
      realName: "Real Name",
      role: "Rifler",
      game: "CS2",
      rank: "Faceit 8",
      country: "🇧🇩",
      bio: "Consistent rifler.",
      stats: { kd: "1.2", hs: "40%", winRate: "66%" },
      social: { twitter: "#", twitch: "#" },
      avatar: `https://ui-avatars.com/api/?name=Player7&background=7C3AED&color=fff&size=128`,
      isCaptain: false,
    },
  ],

  matches: [
    {
      id: 1,
      opponent: "Team Alpha",
      game: "Valorant",
      result: "WIN",
      score: "13 - 7",
      map: "Ascent",
      date: "2025-01-15",
      tournament: "Community Cup #3",
    },
    {
      id: 2,
      opponent: "Rival Squad",
      game: "CS2",
      result: "LOSS",
      score: "14 - 16",
      map: "Mirage",
      date: "2025-01-20",
      tournament: "Faceit League",
    },
    {
      id: 3,
      opponent: "Eclipse Esports",
      game: "Valorant",
      result: "WIN",
      score: "13 - 9",
      map: "Bind",
      date: "2025-01-22",
      tournament: "Weekly Showdown",
    },
    {
      id: 4,
      opponent: "Phoenix Gaming",
      game: "Valorant",
      result: "WIN",
      score: "13 - 11",
      map: "Haven",
      date: "2025-01-25",
      tournament: "Community Cup #4",
    },
    {
      id: 5,
      opponent: "Storm Esports",
      game: "CS2",
      result: "WIN",
      score: "16 - 12",
      map: "Inferno",
      date: "2025-01-28",
      tournament: "Faceit League",
    },
  ],

  achievements: [
    { title: "1st Place", event: "Community Valorant Cup", year: "2024", game: "Valorant" },
    { title: "Top 8", event: "Regional CS2 Open", year: "2024", game: "CS2" },
    { title: "2nd Place", event: "Weekly Showdown Finals", year: "2024", game: "Valorant" },
    { title: "3rd Place", event: "Bangladesh Esports League", year: "2024", game: "Valorant" },
  ],
};

/** Upcoming match placeholder - extend Match type if needed */
export const upcomingMatches = [
  {
    id: 101,
    opponent: "TBD",
    game: "Valorant",
    date: "2025-02-28",
    tournament: "Community Cup #5",
    time: "20:00 BDT",
  },
];
